// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CDrxi3YieOJBuPWP6foP5D65eeKvMhc',
    appId: '1:1085309164472:web:dcd8835c2b62b4fff5cd4d',
    messagingSenderId: '1085309164472',
    projectId: 'chatbob-bed9e',
    authDomain: 'chatbob-bed9e.firebaseapp.com',
    storageBucket: 'chatbob-bed9e.firebasestorage.app',
    measurementId: 'G-EMVP134EDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkm1soDSSBz05pFcg-uXYZTNCx-HrWkY',
    appId: '1:1085309164472:android:0e73f7bdac289477f5cd4d',
    messagingSenderId: '1085309164472',
    projectId: 'chatbob-bed9e',
    storageBucket: 'chatbob-bed9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJhaF_N9vzQqGF5FDkjN1ekMi72SHV14',
    appId: '1:1085309164472:ios:0d790f5ae9127f32f5cd4d',
    messagingSenderId: '1085309164472',
    projectId: 'chatbob-bed9e',
    storageBucket: 'chatbob-bed9e.firebasestorage.app',
    iosBundleId: 'com.example.chatbotChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJhaF_N9vzQqGF5FDkjN1ekMi72SHV14',
    appId: '1:1085309164472:ios:0d790f5ae9127f32f5cd4d',
    messagingSenderId: '1085309164472',
    projectId: 'chatbob-bed9e',
    storageBucket: 'chatbob-bed9e.firebasestorage.app',
    iosBundleId: 'com.example.chatbotChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8CDrxi3YieOJBuPWP6foP5D65eeKvMhc',
    appId: '1:1085309164472:web:10b7beb40bf67f82f5cd4d',
    messagingSenderId: '1085309164472',
    projectId: 'chatbob-bed9e',
    authDomain: 'chatbob-bed9e.firebaseapp.com',
    storageBucket: 'chatbob-bed9e.firebasestorage.app',
    measurementId: 'G-F9PLCD26P0',
  );
}
